feat: add updated scripts

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -6,51 +6,37 @@
 # and managing release notes for a BOSH Release pipeline
 #
 # author:  James Hunt <james@niftylogic.com>
+# created: 2016-03-30
 
 set -eu
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 header() {
-  echo
-  echo "###############################################"
-  echo
-  echo $*
-  echo
+	echo
+	echo "###############################################"
+	echo
+	echo $*
+	echo
 }
 
-######
-######
-######
-header "Checking the Concourse Pipeline Environment"
-envok=0
-checkenv() {
-  local name=$1
-  local val=$2
+: ${REPO_ROOT:?required}
+: ${RELEASE_ROOT:?required}
+: ${REPO_OUT:?required}
+: ${BRANCH:?required}
+: ${GITHUB_OWNER:?required}
+: ${VERSION_FROM:?required}
+: ${AWS_ACCESS_KEY:?required}
+: ${AWS_SECRET_KEY:?required}
+: ${GIT_EMAIL:?required}
+: ${GIT_NAME:?required}
 
-  if [[ -z "$val" ]]; then
-    echo >&2 "The $name variable must be set."
-    envok=1
-  fi
-}
-checkenv REPO_ROOT      "${REPO_ROOT:-}"
-checkenv RELEASE_ROOT   "${RELEASE_ROOT:-}"
-checkenv REPO_OUT       "${REPO_OUT:-}"
-checkenv BRANCH         "${BRANCH:-}"
-checkenv GITHUB_OWNER   "${GITHUB_OWNER:-}"
-checkenv VERSION_FROM   "${VERSION_FROM:-}"
-checkenv AWS_ACCESS_KEY "${AWS_ACCESS_KEY:-}"
-checkenv AWS_SECRET_KEY "${AWS_SECRET_KEY:-}"
-checkenv GIT_EMAIL      "${GIT_EMAIL:-}"
-checkenv GIT_NAME       "${GIT_NAME:-}"
-if [[ $envok != 0 ]]; then
-  echo >&2 "Is your Concourse Pipeline misconfigured?"
-  exit 1
+if [[ ! -f ${VERSION_FROM} ]]; then
+  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
+  exit 2
 fi
-
 VERSION=$(cat ${VERSION_FROM})
-if [[ -z "${VERSION}" ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty."
-  exit 1
+if [[ -z ${VERSION} ]]; then
+  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
+  exit 2
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
@@ -58,15 +44,15 @@ if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
   exit 1
 fi
 
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
 ###############################################################
 
-cd ${REPO_ROOT}
+git clone ${REPO_ROOT} ${REPO_OUT}
+
+pushd ${REPO_OUT}
 RELEASE_NAME=$(bosh int config/final.yml --path /final_name)
 
-######
-######
-######
-header "Configuring blobstore (AWS)"
 cat > config/private.yml <<YAML
 ---
 blobstore:
@@ -76,45 +62,42 @@ blobstore:
     secret_access_key: ${AWS_SECRET_KEY}
 YAML
 
-######
-######
-######
-header "Creating final release..."
+header "Pulling in any git submodules..."
+git submodule update --init --recursive --force
+
+header "Create final release..."
 bosh -n create-release --final --version "${VERSION}"
 bosh -n create-release releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.yml \
               --tarball releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.tgz
-cd -
+popd
 
-RELEASE_TGZ=$REPO_ROOT/releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.tgz
-export SHA1=$(sha1sum $RELEASE_TGZ | head -n1 | awk '{print $1}')
-echo "SHA1=$SHA1"
+RELEASE_TGZ=$REPO_OUT/releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.tgz
+export RELEASE_SHA1=$(sha1sum $RELEASE_TGZ | head -n1 | awk '{print $1}')
+export RELEASE_URL="https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/download/v${VERSION}/${RELEASE_NAME}-${VERSION}.tgz"
+echo "RELEASE_SHA1=$RELEASE_SHA1"
 
 mkdir -p ${RELEASE_ROOT}/artifacts
 echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
-echo "${RELEASE_NAME} v${VERSION}"         > ${RELEASE_ROOT}/name
-mv ${REPO_ROOT}/releases/*/*-${VERSION}.tgz  ${RELEASE_ROOT}/artifacts
-mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
+echo "v${VERSION}"                         > ${RELEASE_ROOT}/name
+mv ${REPO_OUT}/releases/*/*-${VERSION}.tgz   ${RELEASE_ROOT}/artifacts
+mv ${REPO_OUT}/ci/release_notes.md           ${RELEASE_ROOT}/notes.md
 cat >> ${RELEASE_ROOT}/notes.md <<EOF
 
 ### Deployment
-
 \`\`\`yaml
 releases:
 - name:    $RELEASE_NAME
   version: $VERSION
-  url:     https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/download/v${VERSION}/${RELEASE_NAME}-${VERSION}.tgz
-  sha1:    $SHA1
+  url:     $RELEASE_URL
+  sha1:    $RELEASE_SHA1
 \`\`\`
 EOF
 cat > ${RELEASE_ROOT}/notification <<EOF
-New ${RELEASE_NAME} v${VERSION} released!
+<!here> New ${RELEASE_NAME} v${VERSION} released!
 EOF
 
 
-######
-######
-######
-header "Updating git repo with final release..."
+header "Update git repo with final release..."
 if [[ -z $(git config --global user.email) ]]; then
   git config --global user.email "${GIT_EMAIL}"
 fi
@@ -122,36 +105,15 @@ if [[ -z $(git config --global user.name) ]]; then
   git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_ROOT}
- shopt -s nullglob
- for MANIFEST_PATH in manifests/*.yml; do
-   len=$(wc -l $MANIFEST_PATH | awk '{print $1}')
-   head=$(head -n `expr $len - 4` $MANIFEST_PATH)
-   cat > $MANIFEST_PATH <<EOF
-${head}
-- name:    $RELEASE_NAME
-  version: $VERSION
-  url:     https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/download/v${VERSION}/${RELEASE_NAME}-${VERSION}.tgz
-  sha1:    $SHA1
-EOF
- done
- git merge --no-edit ${BRANCH}
- git add -A
- git status
- git commit -m "release v${VERSION}")
+pushd $REPO_OUT
+$DIR/update-manifest-release $RELEASE_NAME $VERSION $RELEASE_URL $RELEASE_SHA1
 
-# so that future steps in the pipeline can push our changes
-cp -a ${REPO_ROOT} ${REPO_OUT}
+git merge --no-edit ${BRANCH}
+git add -A
+git status
+git commit -m "release v${VERSION}"
+popd
 
-######
-######
-######
-header "Setting up notifications files"
-echo "New ${RELEASE_NAME} v${VERSION} released." > notifications/message
-echo "https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/tag/v${VERSION}" > notifications/link
-
-echo
-echo
-echo
-echo "SUCCESS"
-exit 0
+cat > ${NOTIFICATION_OUT:-notifications}/message <<EOS
+New ${RELEASE_NAME} v${VERSION} released. <https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/tag/v${VERSION}|Release notes>.
+EOS
